# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: equipment_response.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import common_pb2
import equipment_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='equipment_response.proto',
  package='',
  serialized_pb='\n\x18\x65quipment_response.proto\x1a\x0c\x63ommon.proto\x1a\x0f\x65quipment.proto\"U\n\x14GetEquipmentResponse\x12\x1c\n\x03res\x18\x01 \x02(\x0b\x32\x0f.CommonResponse\x12\x1f\n\tequipment\x18\x02 \x03(\x0b\x32\x0c.EquipmentPB\"g\n\x18\x45nhanceEquipmentResponse\x12\x1c\n\x03res\x18\x01 \x02(\x0b\x32\x0f.CommonResponse\x12\x0b\n\x03num\x18\x03 \x01(\x05\x12 \n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x12.EnhanceDataFormat\"S\n\x18\x43omposeEquipmentResponse\x12\x1c\n\x03res\x18\x01 \x02(\x0b\x32\x0f.CommonResponse\x12\x19\n\x03\x65qu\x18\x02 \x01(\x0b\x32\x0c.EquipmentPB\"x\n\x18NobbingEquipmentResponse\x12\x1c\n\x03res\x18\x01 \x02(\x0b\x32\x0f.CommonResponse\x12\x19\n\x03\x65qu\x18\x02 \x01(\x0b\x32\x0c.EquipmentPB\x12#\n\x03\x63gr\x18\x03 \x01(\x0b\x32\x16.GameResourcesResponse\"]\n\x18MeltingEquipmentResponse\x12\x1c\n\x03res\x18\x01 \x02(\x0b\x32\x0f.CommonResponse\x12#\n\x03\x63gr\x18\x02 \x01(\x0b\x32\x16.GameResourcesResponse\"_\n\x1a\x41wakeningEquipmentResponse\x12\x1c\n\x03res\x18\x01 \x02(\x0b\x32\x0f.CommonResponse\x12#\n\x03\x63gr\x18\x02 \x01(\x0b\x32\x16.GameResourcesResponse')




_GETEQUIPMENTRESPONSE = _descriptor.Descriptor(
  name='GetEquipmentResponse',
  full_name='GetEquipmentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='GetEquipmentResponse.res', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='equipment', full_name='GetEquipmentResponse.equipment', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=59,
  serialized_end=144,
)


_ENHANCEEQUIPMENTRESPONSE = _descriptor.Descriptor(
  name='EnhanceEquipmentResponse',
  full_name='EnhanceEquipmentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='EnhanceEquipmentResponse.res', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num', full_name='EnhanceEquipmentResponse.num', index=1,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='EnhanceEquipmentResponse.data', index=2,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=146,
  serialized_end=249,
)


_COMPOSEEQUIPMENTRESPONSE = _descriptor.Descriptor(
  name='ComposeEquipmentResponse',
  full_name='ComposeEquipmentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='ComposeEquipmentResponse.res', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='equ', full_name='ComposeEquipmentResponse.equ', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=251,
  serialized_end=334,
)


_NOBBINGEQUIPMENTRESPONSE = _descriptor.Descriptor(
  name='NobbingEquipmentResponse',
  full_name='NobbingEquipmentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='NobbingEquipmentResponse.res', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='equ', full_name='NobbingEquipmentResponse.equ', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cgr', full_name='NobbingEquipmentResponse.cgr', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=336,
  serialized_end=456,
)


_MELTINGEQUIPMENTRESPONSE = _descriptor.Descriptor(
  name='MeltingEquipmentResponse',
  full_name='MeltingEquipmentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='MeltingEquipmentResponse.res', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cgr', full_name='MeltingEquipmentResponse.cgr', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=458,
  serialized_end=551,
)


_AWAKENINGEQUIPMENTRESPONSE = _descriptor.Descriptor(
  name='AwakeningEquipmentResponse',
  full_name='AwakeningEquipmentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='AwakeningEquipmentResponse.res', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cgr', full_name='AwakeningEquipmentResponse.cgr', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=553,
  serialized_end=648,
)

_GETEQUIPMENTRESPONSE.fields_by_name['res'].message_type = common_pb2._COMMONRESPONSE
_GETEQUIPMENTRESPONSE.fields_by_name['equipment'].message_type = equipment_pb2._EQUIPMENTPB
_ENHANCEEQUIPMENTRESPONSE.fields_by_name['res'].message_type = common_pb2._COMMONRESPONSE
_ENHANCEEQUIPMENTRESPONSE.fields_by_name['data'].message_type = equipment_pb2._ENHANCEDATAFORMAT
_COMPOSEEQUIPMENTRESPONSE.fields_by_name['res'].message_type = common_pb2._COMMONRESPONSE
_COMPOSEEQUIPMENTRESPONSE.fields_by_name['equ'].message_type = equipment_pb2._EQUIPMENTPB
_NOBBINGEQUIPMENTRESPONSE.fields_by_name['res'].message_type = common_pb2._COMMONRESPONSE
_NOBBINGEQUIPMENTRESPONSE.fields_by_name['equ'].message_type = equipment_pb2._EQUIPMENTPB
_NOBBINGEQUIPMENTRESPONSE.fields_by_name['cgr'].message_type = common_pb2._GAMERESOURCESRESPONSE
_MELTINGEQUIPMENTRESPONSE.fields_by_name['res'].message_type = common_pb2._COMMONRESPONSE
_MELTINGEQUIPMENTRESPONSE.fields_by_name['cgr'].message_type = common_pb2._GAMERESOURCESRESPONSE
_AWAKENINGEQUIPMENTRESPONSE.fields_by_name['res'].message_type = common_pb2._COMMONRESPONSE
_AWAKENINGEQUIPMENTRESPONSE.fields_by_name['cgr'].message_type = common_pb2._GAMERESOURCESRESPONSE
DESCRIPTOR.message_types_by_name['GetEquipmentResponse'] = _GETEQUIPMENTRESPONSE
DESCRIPTOR.message_types_by_name['EnhanceEquipmentResponse'] = _ENHANCEEQUIPMENTRESPONSE
DESCRIPTOR.message_types_by_name['ComposeEquipmentResponse'] = _COMPOSEEQUIPMENTRESPONSE
DESCRIPTOR.message_types_by_name['NobbingEquipmentResponse'] = _NOBBINGEQUIPMENTRESPONSE
DESCRIPTOR.message_types_by_name['MeltingEquipmentResponse'] = _MELTINGEQUIPMENTRESPONSE
DESCRIPTOR.message_types_by_name['AwakeningEquipmentResponse'] = _AWAKENINGEQUIPMENTRESPONSE

class GetEquipmentResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETEQUIPMENTRESPONSE

  # @@protoc_insertion_point(class_scope:GetEquipmentResponse)

class EnhanceEquipmentResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENHANCEEQUIPMENTRESPONSE

  # @@protoc_insertion_point(class_scope:EnhanceEquipmentResponse)

class ComposeEquipmentResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COMPOSEEQUIPMENTRESPONSE

  # @@protoc_insertion_point(class_scope:ComposeEquipmentResponse)

class NobbingEquipmentResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NOBBINGEQUIPMENTRESPONSE

  # @@protoc_insertion_point(class_scope:NobbingEquipmentResponse)

class MeltingEquipmentResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MELTINGEQUIPMENTRESPONSE

  # @@protoc_insertion_point(class_scope:MeltingEquipmentResponse)

class AwakeningEquipmentResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AWAKENINGEQUIPMENTRESPONSE

  # @@protoc_insertion_point(class_scope:AwakeningEquipmentResponse)


# @@protoc_insertion_point(module_scope)
