# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: friend.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import common_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='friend.proto',
  package='',
  serialized_pb='\n\x0c\x66riend.proto\x1a\x0c\x63ommon.proto\"!\n\x0c\x46riendCommon\x12\x11\n\ttarget_id\x18\x01 \x02(\x05\"#\n\x11\x41\x64\x64\x46riendResponse\x12\x0e\n\x06result\x18\x01 \x02(\x08')




_FRIENDCOMMON = _descriptor.Descriptor(
  name='FriendCommon',
  full_name='FriendCommon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target_id', full_name='FriendCommon.target_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=30,
  serialized_end=63,
)


_ADDFRIENDRESPONSE = _descriptor.Descriptor(
  name='AddFriendResponse',
  full_name='AddFriendResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='AddFriendResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=65,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['FriendCommon'] = _FRIENDCOMMON
DESCRIPTOR.message_types_by_name['AddFriendResponse'] = _ADDFRIENDRESPONSE

class FriendCommon(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FRIENDCOMMON

  # @@protoc_insertion_point(class_scope:FriendCommon)

class AddFriendResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADDFRIENDRESPONSE

  # @@protoc_insertion_point(class_scope:AddFriendResponse)


# @@protoc_insertion_point(module_scope)
