# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hero_chip.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hero_chip.proto',
  package='',
  serialized_pb='\n\x0fhero_chip.proto\"9\n\nHeroChipPB\x12\x14\n\x0chero_chip_no\x18\x01 \x02(\x05\x12\x15\n\rhero_chip_num\x18\x02 \x02(\x05')




_HEROCHIPPB = _descriptor.Descriptor(
  name='HeroChipPB',
  full_name='HeroChipPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hero_chip_no', full_name='HeroChipPB.hero_chip_no', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hero_chip_num', full_name='HeroChipPB.hero_chip_num', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=19,
  serialized_end=76,
)

DESCRIPTOR.message_types_by_name['HeroChipPB'] = _HEROCHIPPB

class HeroChipPB(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HEROCHIPPB

  # @@protoc_insertion_point(class_scope:HeroChipPB)


# @@protoc_insertion_point(module_scope)
