# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hero_request.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import hero_chip_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hero_request.proto',
  package='',
  serialized_pb='\n\x12hero_request.proto\x1a\x0fhero_chip.proto\"X\n\x1aHeroUpgradeWithItemRequest\x12\x0f\n\x07hero_no\x18\x01 \x02(\x05\x12\x13\n\x0b\x65xp_item_no\x18\x02 \x02(\x05\x12\x14\n\x0c\x65xp_item_num\x18\x03 \x02(\x05\"#\n\x10HeroBreakRequest\x12\x0f\n\x07hero_no\x18\x01 \x02(\x05\"I\n\x14HeroSacrificeRequest\x12\x10\n\x08hero_nos\x18\x01 \x03(\x05\x12\x1f\n\nhero_chips\x18\x02 \x03(\x0b\x32\x0b.HeroChipPB\"*\n\x12HeroComposeRequest\x12\x14\n\x0chero_chip_no\x18\x01 \x02(\x05\"#\n\x0fHeroSellRequest\x12\x10\n\x08hero_nos\x18\x01 \x03(\x05\"4\n\x11HeroRefineRequest\x12\x0f\n\x07hero_no\x18\x01 \x02(\x05\x12\x0e\n\x06refine\x18\x02 \x02(\x05\"\x1e\n\x0bHeroRequest\x12\x0f\n\x07hero_no\x18\x01 \x02(\x05\";\n\x10HeroAwakeRequest\x12\x0f\n\x07hero_no\x18\x01 \x02(\x05\x12\x16\n\x0e\x61wake_item_num\x18\x02 \x01(\x05\".\n\x1bHeroBreakRelatedInfoRequest\x12\x0f\n\x07hero_no\x18\x01 \x02(\x05')




_HEROUPGRADEWITHITEMREQUEST = _descriptor.Descriptor(
  name='HeroUpgradeWithItemRequest',
  full_name='HeroUpgradeWithItemRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hero_no', full_name='HeroUpgradeWithItemRequest.hero_no', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exp_item_no', full_name='HeroUpgradeWithItemRequest.exp_item_no', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exp_item_num', full_name='HeroUpgradeWithItemRequest.exp_item_num', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=39,
  serialized_end=127,
)


_HEROBREAKREQUEST = _descriptor.Descriptor(
  name='HeroBreakRequest',
  full_name='HeroBreakRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hero_no', full_name='HeroBreakRequest.hero_no', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=129,
  serialized_end=164,
)


_HEROSACRIFICEREQUEST = _descriptor.Descriptor(
  name='HeroSacrificeRequest',
  full_name='HeroSacrificeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hero_nos', full_name='HeroSacrificeRequest.hero_nos', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hero_chips', full_name='HeroSacrificeRequest.hero_chips', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=166,
  serialized_end=239,
)


_HEROCOMPOSEREQUEST = _descriptor.Descriptor(
  name='HeroComposeRequest',
  full_name='HeroComposeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hero_chip_no', full_name='HeroComposeRequest.hero_chip_no', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=241,
  serialized_end=283,
)


_HEROSELLREQUEST = _descriptor.Descriptor(
  name='HeroSellRequest',
  full_name='HeroSellRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hero_nos', full_name='HeroSellRequest.hero_nos', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=285,
  serialized_end=320,
)


_HEROREFINEREQUEST = _descriptor.Descriptor(
  name='HeroRefineRequest',
  full_name='HeroRefineRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hero_no', full_name='HeroRefineRequest.hero_no', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='refine', full_name='HeroRefineRequest.refine', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=322,
  serialized_end=374,
)


_HEROREQUEST = _descriptor.Descriptor(
  name='HeroRequest',
  full_name='HeroRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hero_no', full_name='HeroRequest.hero_no', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=376,
  serialized_end=406,
)


_HEROAWAKEREQUEST = _descriptor.Descriptor(
  name='HeroAwakeRequest',
  full_name='HeroAwakeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hero_no', full_name='HeroAwakeRequest.hero_no', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='awake_item_num', full_name='HeroAwakeRequest.awake_item_num', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=408,
  serialized_end=467,
)


_HEROBREAKRELATEDINFOREQUEST = _descriptor.Descriptor(
  name='HeroBreakRelatedInfoRequest',
  full_name='HeroBreakRelatedInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hero_no', full_name='HeroBreakRelatedInfoRequest.hero_no', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=469,
  serialized_end=515,
)

_HEROSACRIFICEREQUEST.fields_by_name['hero_chips'].message_type = hero_chip_pb2._HEROCHIPPB
DESCRIPTOR.message_types_by_name['HeroUpgradeWithItemRequest'] = _HEROUPGRADEWITHITEMREQUEST
DESCRIPTOR.message_types_by_name['HeroBreakRequest'] = _HEROBREAKREQUEST
DESCRIPTOR.message_types_by_name['HeroSacrificeRequest'] = _HEROSACRIFICEREQUEST
DESCRIPTOR.message_types_by_name['HeroComposeRequest'] = _HEROCOMPOSEREQUEST
DESCRIPTOR.message_types_by_name['HeroSellRequest'] = _HEROSELLREQUEST
DESCRIPTOR.message_types_by_name['HeroRefineRequest'] = _HEROREFINEREQUEST
DESCRIPTOR.message_types_by_name['HeroRequest'] = _HEROREQUEST
DESCRIPTOR.message_types_by_name['HeroAwakeRequest'] = _HEROAWAKEREQUEST
DESCRIPTOR.message_types_by_name['HeroBreakRelatedInfoRequest'] = _HEROBREAKRELATEDINFOREQUEST

class HeroUpgradeWithItemRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HEROUPGRADEWITHITEMREQUEST

  # @@protoc_insertion_point(class_scope:HeroUpgradeWithItemRequest)

class HeroBreakRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HEROBREAKREQUEST

  # @@protoc_insertion_point(class_scope:HeroBreakRequest)

class HeroSacrificeRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HEROSACRIFICEREQUEST

  # @@protoc_insertion_point(class_scope:HeroSacrificeRequest)

class HeroComposeRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HEROCOMPOSEREQUEST

  # @@protoc_insertion_point(class_scope:HeroComposeRequest)

class HeroSellRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HEROSELLREQUEST

  # @@protoc_insertion_point(class_scope:HeroSellRequest)

class HeroRefineRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HEROREFINEREQUEST

  # @@protoc_insertion_point(class_scope:HeroRefineRequest)

class HeroRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HEROREQUEST

  # @@protoc_insertion_point(class_scope:HeroRequest)

class HeroAwakeRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HEROAWAKEREQUEST

  # @@protoc_insertion_point(class_scope:HeroAwakeRequest)

class HeroBreakRelatedInfoRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HEROBREAKRELATEDINFOREQUEST

  # @@protoc_insertion_point(class_scope:HeroBreakRelatedInfoRequest)


# @@protoc_insertion_point(module_scope)
