# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kuaiyong.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import common_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='kuaiyong.proto',
  package='',
  serialized_pb='\n\x0ekuaiyong.proto\x1a\x0c\x63ommon.proto\")\n\x16KuaiyongFlowIdResponse\x12\x0f\n\x07\x66low_id\x18\x01 \x01(\t\"~\n\x18KuaiyongRechargeResponse\x12\x1c\n\x03res\x18\x01 \x02(\x0b\x32\x0f.CommonResponse\x12$\n\x04gain\x18\x02 \x01(\x0b\x32\x16.GameResourcesResponse\x12\x1e\n\x04info\x18\x03 \x01(\x0b\x32\x10.GetGoldResponse')




_KUAIYONGFLOWIDRESPONSE = _descriptor.Descriptor(
  name='KuaiyongFlowIdResponse',
  full_name='KuaiyongFlowIdResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='flow_id', full_name='KuaiyongFlowIdResponse.flow_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=32,
  serialized_end=73,
)


_KUAIYONGRECHARGERESPONSE = _descriptor.Descriptor(
  name='KuaiyongRechargeResponse',
  full_name='KuaiyongRechargeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='KuaiyongRechargeResponse.res', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gain', full_name='KuaiyongRechargeResponse.gain', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='info', full_name='KuaiyongRechargeResponse.info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=75,
  serialized_end=201,
)

_KUAIYONGRECHARGERESPONSE.fields_by_name['res'].message_type = common_pb2._COMMONRESPONSE
_KUAIYONGRECHARGERESPONSE.fields_by_name['gain'].message_type = common_pb2._GAMERESOURCESRESPONSE
_KUAIYONGRECHARGERESPONSE.fields_by_name['info'].message_type = common_pb2._GETGOLDRESPONSE
DESCRIPTOR.message_types_by_name['KuaiyongFlowIdResponse'] = _KUAIYONGFLOWIDRESPONSE
DESCRIPTOR.message_types_by_name['KuaiyongRechargeResponse'] = _KUAIYONGRECHARGERESPONSE

class KuaiyongFlowIdResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _KUAIYONGFLOWIDRESPONSE

  # @@protoc_insertion_point(class_scope:KuaiyongFlowIdResponse)

class KuaiyongRechargeResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _KUAIYONGRECHARGERESPONSE

  # @@protoc_insertion_point(class_scope:KuaiyongRechargeResponse)


# @@protoc_insertion_point(module_scope)
