# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: push.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import common_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='push.proto',
  package='',
  serialized_pb='\n\npush.proto\x1a\x0c\x63ommon.proto\"#\n\x0cregisterPush\x12\x13\n\x0b\x64\x65viceToken\x18\x01 \x02(\t\"/\n\x0fregisterPushRes\x12\x1c\n\x03res\x18\x01 \x02(\x0b\x32\x0f.CommonResponse\"-\n\tmsgSwitch\x12\x10\n\x08msg_type\x18\x01 \x02(\x05\x12\x0e\n\x06switch\x18\x02 \x02(\x05\"*\n\x0cmsgSwitchReq\x12\x1a\n\x06switch\x18\x01 \x03(\x0b\x32\n.msgSwitch\"*\n\x0cmsgSwitchRes\x12\x1a\n\x06switch\x18\x01 \x03(\x0b\x32\n.msgSwitch')




_REGISTERPUSH = _descriptor.Descriptor(
  name='registerPush',
  full_name='registerPush',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deviceToken', full_name='registerPush.deviceToken', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=28,
  serialized_end=63,
)


_REGISTERPUSHRES = _descriptor.Descriptor(
  name='registerPushRes',
  full_name='registerPushRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='registerPushRes.res', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=65,
  serialized_end=112,
)


_MSGSWITCH = _descriptor.Descriptor(
  name='msgSwitch',
  full_name='msgSwitch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg_type', full_name='msgSwitch.msg_type', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='switch', full_name='msgSwitch.switch', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=114,
  serialized_end=159,
)


_MSGSWITCHREQ = _descriptor.Descriptor(
  name='msgSwitchReq',
  full_name='msgSwitchReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='switch', full_name='msgSwitchReq.switch', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=161,
  serialized_end=203,
)


_MSGSWITCHRES = _descriptor.Descriptor(
  name='msgSwitchRes',
  full_name='msgSwitchRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='switch', full_name='msgSwitchRes.switch', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=205,
  serialized_end=247,
)

_REGISTERPUSHRES.fields_by_name['res'].message_type = common_pb2._COMMONRESPONSE
_MSGSWITCHREQ.fields_by_name['switch'].message_type = _MSGSWITCH
_MSGSWITCHRES.fields_by_name['switch'].message_type = _MSGSWITCH
DESCRIPTOR.message_types_by_name['registerPush'] = _REGISTERPUSH
DESCRIPTOR.message_types_by_name['registerPushRes'] = _REGISTERPUSHRES
DESCRIPTOR.message_types_by_name['msgSwitch'] = _MSGSWITCH
DESCRIPTOR.message_types_by_name['msgSwitchReq'] = _MSGSWITCHREQ
DESCRIPTOR.message_types_by_name['msgSwitchRes'] = _MSGSWITCHRES

class registerPush(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REGISTERPUSH

  # @@protoc_insertion_point(class_scope:registerPush)

class registerPushRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REGISTERPUSHRES

  # @@protoc_insertion_point(class_scope:registerPushRes)

class msgSwitch(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MSGSWITCH

  # @@protoc_insertion_point(class_scope:msgSwitch)

class msgSwitchReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MSGSWITCHREQ

  # @@protoc_insertion_point(class_scope:msgSwitchReq)

class msgSwitchRes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MSGSWITCHRES

  # @@protoc_insertion_point(class_scope:msgSwitchRes)


# @@protoc_insertion_point(module_scope)
