# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Share.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import common_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Share.proto',
  package='',
  serialized_pb='\n\x0bShare.proto\x1a\x0c\x63ommon.proto\"\x1a\n\x18\x43lientGetShareStatusData\"\'\n\x14\x43lientGetShareReward\x12\x0f\n\x07task_id\x18\x01 \x02(\x05\"(\n\x15ServerShareStatusData\x12\x0f\n\x07task_id\x18\x01 \x03(\x05')




_CLIENTGETSHARESTATUSDATA = _descriptor.Descriptor(
  name='ClientGetShareStatusData',
  full_name='ClientGetShareStatusData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=29,
  serialized_end=55,
)


_CLIENTGETSHAREREWARD = _descriptor.Descriptor(
  name='ClientGetShareReward',
  full_name='ClientGetShareReward',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='ClientGetShareReward.task_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=57,
  serialized_end=96,
)


_SERVERSHARESTATUSDATA = _descriptor.Descriptor(
  name='ServerShareStatusData',
  full_name='ServerShareStatusData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='ServerShareStatusData.task_id', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=98,
  serialized_end=138,
)

DESCRIPTOR.message_types_by_name['ClientGetShareStatusData'] = _CLIENTGETSHARESTATUSDATA
DESCRIPTOR.message_types_by_name['ClientGetShareReward'] = _CLIENTGETSHAREREWARD
DESCRIPTOR.message_types_by_name['ServerShareStatusData'] = _SERVERSHARESTATUSDATA

class ClientGetShareStatusData(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CLIENTGETSHARESTATUSDATA

  # @@protoc_insertion_point(class_scope:ClientGetShareStatusData)

class ClientGetShareReward(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CLIENTGETSHAREREWARD

  # @@protoc_insertion_point(class_scope:ClientGetShareReward)

class ServerShareStatusData(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SERVERSHARESTATUSDATA

  # @@protoc_insertion_point(class_scope:ServerShareStatusData)


# @@protoc_insertion_point(module_scope)
