# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: soul_shop.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import common_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='soul_shop.proto',
  package='',
  serialized_pb='\n\x0fsoul_shop.proto\x1a\x0c\x63ommon.proto')





# @@protoc_insertion_point(module_scope)
