# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tencent.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tencent.proto',
  package='',
  serialized_pb='\n\rtencent.proto\"\x1f\n\x0fGetGoldResponse\x12\x0c\n\x04gold\x18\x01 \x02(\x05')




_GETGOLDRESPONSE = _descriptor.Descriptor(
  name='GetGoldResponse',
  full_name='GetGoldResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gold', full_name='GetGoldResponse.gold', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=17,
  serialized_end=48,
)

DESCRIPTOR.message_types_by_name['GetGoldResponse'] = _GETGOLDRESPONSE

class GetGoldResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETGOLDRESPONSE

  # @@protoc_insertion_point(class_scope:GetGoldResponse)


# @@protoc_insertion_point(module_scope)
