# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: travel_shoes.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='travel_shoes.proto',
  package='',
  serialized_pb='\n\x12travel_shoes.proto\"1\n\tShoesInfo\x12\x12\n\nshoes_type\x18\x01 \x02(\x05\x12\x10\n\x08shoes_no\x18\x02 \x02(\x05')




_SHOESINFO = _descriptor.Descriptor(
  name='ShoesInfo',
  full_name='ShoesInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shoes_type', full_name='ShoesInfo.shoes_type', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shoes_no', full_name='ShoesInfo.shoes_no', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=71,
)

DESCRIPTOR.message_types_by_name['ShoesInfo'] = _SHOESINFO

class ShoesInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SHOESINFO

  # @@protoc_insertion_point(class_scope:ShoesInfo)


# @@protoc_insertion_point(module_scope)
